//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 06:46:38 PM CEST 
//


package com.project.megatravel.model.users;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.project.megatravel.model.accomodation.Lokacija;
import com.project.megatravel.model.reservations.Komentar;
import com.project.megatravel.model.reservations.TRezervacija;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{www.model.megatravel.project.com/users}TKorisnik">
 *       &lt;sequence>
 *         &lt;element name="kategorija">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="BRONZE"/>
 *               &lt;enumeration value="SILVER"/>
 *               &lt;enumeration value="GOLD"/>
 *               &lt;enumeration value="PLATINUM"/>
 *               &lt;enumeration value="NA"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ponudjenPopustNakonOtkazivanja" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="lokacija" type="{www.model.megatravel.project.com/accomodation}TLokacija"/>
 *         &lt;element name="ime">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="prezime">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="stanje">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="AKTIVAN"/>
 *               &lt;enumeration value="BLOKIRAN"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="rezervacije" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{www.model.megatravel.project.com/reservations}TRezervacija">
 *                 &lt;sequence>
 *                   &lt;element name="cenaSmestaja">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="stanje">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="REZERVISANO"/>
 *                         &lt;enumeration value="U TOKU"/>
 *                         &lt;enumeration value="OTKAZANO"/>
 *                         &lt;enumeration value="REALIZOVANO"/>
 *                         &lt;enumeration value="U OBRADI"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="korisnik" type="{www.model.megatravel.project.com/users}TKorisnik"/>
 *                   &lt;element name="ocena" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="komentar" type="{www.model.megatravel.project.com/reservations}TKomentar"/>
 *                   &lt;element name="obradjeno" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="datumRezervacije">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                       &lt;minInclusive value="1900-01-01"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="kuponi" type="{www.model.megatravel.project.com/users}TKupon" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kategorija",
    "ponudjenPopustNakonOtkazivanja",
    "lokacija",
    "ime",
    "prezime",
    "stanje",
    "rezervacije",
    "kuponi"
})
@XmlRootElement(name = "KrajnjiKorisnik")
public class KrajnjiKorisnik
    extends TKorisnik
{

    @XmlElement(required = true, defaultValue = "NA")
    protected String kategorija;
    @XmlElement(defaultValue = "false")
    protected boolean ponudjenPopustNakonOtkazivanja;
    @XmlElement(required = true)
    protected Lokacija lokacija;
    @XmlElement(required = true)
    protected String ime;
    @XmlElement(required = true)
    protected String prezime;
    @XmlElement(required = true, defaultValue = "AKTIVAN")
    protected String stanje;
    protected List<KrajnjiKorisnik.Rezervacije> rezervacije;
    protected List<Kupon> kuponi;

    /**
     * Gets the value of the kategorija property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKategorija() {
        return kategorija;
    }

    /**
     * Sets the value of the kategorija property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKategorija(String value) {
        this.kategorija = value;
    }

    /**
     * Gets the value of the ponudjenPopustNakonOtkazivanja property.
     * 
     */
    public boolean isPonudjenPopustNakonOtkazivanja() {
        return ponudjenPopustNakonOtkazivanja;
    }

    /**
     * Sets the value of the ponudjenPopustNakonOtkazivanja property.
     * 
     */
    public void setPonudjenPopustNakonOtkazivanja(boolean value) {
        this.ponudjenPopustNakonOtkazivanja = value;
    }

    /**
     * Gets the value of the lokacija property.
     * 
     * @return
     *     possible object is
     *     {@link Lokacija }
     *     
     */
    public Lokacija getLokacija() {
        return lokacija;
    }

    /**
     * Sets the value of the lokacija property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lokacija }
     *     
     */
    public void setLokacija(Lokacija value) {
        this.lokacija = value;
    }

    /**
     * Gets the value of the ime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIme() {
        return ime;
    }

    /**
     * Sets the value of the ime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIme(String value) {
        this.ime = value;
    }

    /**
     * Gets the value of the prezime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrezime() {
        return prezime;
    }

    /**
     * Sets the value of the prezime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrezime(String value) {
        this.prezime = value;
    }

    /**
     * Gets the value of the stanje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStanje() {
        return stanje;
    }

    /**
     * Sets the value of the stanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStanje(String value) {
        this.stanje = value;
    }

    /**
     * Gets the value of the rezervacije property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rezervacije property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRezervacije().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KrajnjiKorisnik.Rezervacije }
     * 
     * 
     */
    public List<KrajnjiKorisnik.Rezervacije> getRezervacije() {
        if (rezervacije == null) {
            rezervacije = new ArrayList<KrajnjiKorisnik.Rezervacije>();
        }
        return this.rezervacije;
    }

    /**
     * Gets the value of the kuponi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kuponi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKuponi().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Kupon }
     * 
     * 
     */
    public List<Kupon> getKuponi() {
        if (kuponi == null) {
            kuponi = new ArrayList<Kupon>();
        }
        return this.kuponi;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{www.model.megatravel.project.com/reservations}TRezervacija">
     *       &lt;sequence>
     *         &lt;element name="cenaSmestaja">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="stanje">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="REZERVISANO"/>
     *               &lt;enumeration value="U TOKU"/>
     *               &lt;enumeration value="OTKAZANO"/>
     *               &lt;enumeration value="REALIZOVANO"/>
     *               &lt;enumeration value="U OBRADI"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="korisnik" type="{www.model.megatravel.project.com/users}TKorisnik"/>
     *         &lt;element name="ocena" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="komentar" type="{www.model.megatravel.project.com/reservations}TKomentar"/>
     *         &lt;element name="obradjeno" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *       &lt;attribute name="datumRezervacije">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *             &lt;minInclusive value="1900-01-01"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cenaSmestaja",
        "stanje",
        "korisnik",
        "ocena",
        "komentar",
        "obradjeno"
    })
    public static class Rezervacije
        extends TRezervacija
    {

        protected double cenaSmestaja;
        @XmlElement(required = true)
        protected String stanje;
        @XmlElement(required = true)
        protected TKorisnik korisnik;
        protected int ocena;
        @XmlElement(required = true)
        protected Komentar komentar;
        @XmlElement(defaultValue = "false")
        protected boolean obradjeno;
        @XmlAttribute(name = "datumRezervacije")
        @XmlJavaTypeAdapter(Adapter3 .class)
        protected Date datumRezervacije;

        /**
         * Gets the value of the cenaSmestaja property.
         * 
         */
        public double getCenaSmestaja() {
            return cenaSmestaja;
        }

        /**
         * Sets the value of the cenaSmestaja property.
         * 
         */
        public void setCenaSmestaja(double value) {
            this.cenaSmestaja = value;
        }

        /**
         * Gets the value of the stanje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStanje() {
            return stanje;
        }

        /**
         * Sets the value of the stanje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStanje(String value) {
            this.stanje = value;
        }

        /**
         * Gets the value of the korisnik property.
         * 
         * @return
         *     possible object is
         *     {@link TKorisnik }
         *     
         */
        public TKorisnik getKorisnik() {
            return korisnik;
        }

        /**
         * Sets the value of the korisnik property.
         * 
         * @param value
         *     allowed object is
         *     {@link TKorisnik }
         *     
         */
        public void setKorisnik(TKorisnik value) {
            this.korisnik = value;
        }

        /**
         * Gets the value of the ocena property.
         * 
         */
        public int getOcena() {
            return ocena;
        }

        /**
         * Sets the value of the ocena property.
         * 
         */
        public void setOcena(int value) {
            this.ocena = value;
        }

        /**
         * Gets the value of the komentar property.
         * 
         * @return
         *     possible object is
         *     {@link Komentar }
         *     
         */
        public Komentar getKomentar() {
            return komentar;
        }

        /**
         * Sets the value of the komentar property.
         * 
         * @param value
         *     allowed object is
         *     {@link Komentar }
         *     
         */
        public void setKomentar(Komentar value) {
            this.komentar = value;
        }

        /**
         * Gets the value of the obradjeno property.
         * 
         */
        public boolean isObradjeno() {
            return obradjeno;
        }

        /**
         * Sets the value of the obradjeno property.
         * 
         */
        public void setObradjeno(boolean value) {
            this.obradjeno = value;
        }

        /**
         * Gets the value of the datumRezervacije property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Date getDatumRezervacije() {
            return datumRezervacije;
        }

        /**
         * Sets the value of the datumRezervacije property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatumRezervacije(Date value) {
            this.datumRezervacije = value;
        }

    }

}
