//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.12 at 12:59:01 AM CEST 
//


package com.project.megaTravel.model.tim41;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TOtkazivanje complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TOtkazivanje">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Dozvoljeno" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="BrojDana">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CenaOtkazivanja">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TOtkazivanje", propOrder = {
    "dozvoljeno",
    "brojDana",
    "cenaOtkazivanja"
})
public class TOtkazivanje {

    @XmlElement(name = "Dozvoljeno", defaultValue = "false")
    protected boolean dozvoljeno;
    @XmlElement(name = "BrojDana", required = true)
    protected BigInteger brojDana;
    @XmlElement(name = "CenaOtkazivanja")
    protected double cenaOtkazivanja;

    /**
     * Gets the value of the dozvoljeno property.
     * 
     */
    public boolean isDozvoljeno() {
        return dozvoljeno;
    }

    /**
     * Sets the value of the dozvoljeno property.
     * 
     */
    public void setDozvoljeno(boolean value) {
        this.dozvoljeno = value;
    }

    /**
     * Gets the value of the brojDana property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojDana() {
        return brojDana;
    }

    /**
     * Sets the value of the brojDana property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojDana(BigInteger value) {
        this.brojDana = value;
    }

    /**
     * Gets the value of the cenaOtkazivanja property.
     * 
     */
    public double getCenaOtkazivanja() {
        return cenaOtkazivanja;
    }

    /**
     * Sets the value of the cenaOtkazivanja property.
     * 
     */
    public void setCenaOtkazivanja(double value) {
        this.cenaOtkazivanja = value;
    }

}
