//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.12 at 12:59:01 AM CEST 
//


package com.project.megaTravel.model.tim41;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

import com.project.megaTravel.model.tim41.reservations.TKomentar;



/**
 * <p>Java class for TSmestajnaJedinica complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TSmestajnaJedinica">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BrojKreveta" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Balkon" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Slike" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
 *                 &lt;attribute name="putanja" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Rejting" type="{www.megatravel.com/tim41}TRejting"/>
 *         &lt;element name="Objekat" type="{www.megatravel.com/tim41}TSmestajniObjekat"/>
 *         &lt;element name="Komentari" type="{www.megatravel.com/tim41/reservations}TKomentar" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Cenovnici" type="{www.megatravel.com/tim41}TCenovnik" maxOccurs="unbounded"/>
 *         &lt;element name="PodrazumevaniCenovnik" type="{www.megatravel.com/tim41}TCenovnik"/>
 *         &lt;element name="Id">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Opis">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1024"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DodatneUsluge" type="{www.megatravel.com/tim41}TDodatnaUsluga" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Otkazivanje" type="{www.megatravel.com/tim41}TOtkazivanje"/>
 *         &lt;element name="PovecanjeVeciBrojOsoba">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TSmestajnaJedinica", propOrder = {
    "brojKreveta",
    "balkon",
    "slike",
    "rejting",
    "objekat",
    "komentari",
    "cenovnici",
    "podrazumevaniCenovnik",
    "id",
    "opis",
    "dodatneUsluge",
    "otkazivanje",
    "povecanjeVeciBrojOsoba"
})
public class TSmestajnaJedinica {

    @XmlElement(name = "BrojKreveta", required = true)
    protected BigInteger brojKreveta;
    @XmlElement(name = "Balkon", defaultValue = "false")
    protected boolean balkon;
    @XmlElement(name = "Slike", required = true)
    protected List<TSmestajnaJedinica.Slike> slike;
    @XmlElement(name = "Rejting", required = true)
    protected TRejting rejting;
    @XmlElement(name = "Objekat", required = true)
    protected TSmestajniObjekat objekat;
    @XmlElement(name = "Komentari")
    protected List<TKomentar> komentari;
    @XmlElement(name = "Cenovnici", required = true)
    protected List<TCenovnik> cenovnici;
    @XmlElement(name = "PodrazumevaniCenovnik", required = true)
    protected TCenovnik podrazumevaniCenovnik;
    @XmlElement(name = "Id", required = true)
    protected BigInteger id;
    @XmlElement(name = "Opis", required = true)
    protected String opis;
    @XmlElement(name = "DodatneUsluge")
    protected List<TDodatnaUsluga> dodatneUsluge;
    @XmlElement(name = "Otkazivanje", required = true)
    protected TOtkazivanje otkazivanje;
    @XmlElement(name = "PovecanjeVeciBrojOsoba")
    protected double povecanjeVeciBrojOsoba;

    /**
     * Gets the value of the brojKreveta property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojKreveta() {
        return brojKreveta;
    }

    /**
     * Sets the value of the brojKreveta property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojKreveta(BigInteger value) {
        this.brojKreveta = value;
    }

    /**
     * Gets the value of the balkon property.
     * 
     */
    public boolean isBalkon() {
        return balkon;
    }

    /**
     * Sets the value of the balkon property.
     * 
     */
    public void setBalkon(boolean value) {
        this.balkon = value;
    }

    /**
     * Gets the value of the slike property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the slike property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSlike().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSmestajnaJedinica.Slike }
     * 
     * 
     */
    public List<TSmestajnaJedinica.Slike> getSlike() {
        if (slike == null) {
            slike = new ArrayList<TSmestajnaJedinica.Slike>();
        }
        return this.slike;
    }

    /**
     * Gets the value of the rejting property.
     * 
     * @return
     *     possible object is
     *     {@link TRejting }
     *     
     */
    public TRejting getRejting() {
        return rejting;
    }

    /**
     * Sets the value of the rejting property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRejting }
     *     
     */
    public void setRejting(TRejting value) {
        this.rejting = value;
    }

    /**
     * Gets the value of the objekat property.
     * 
     * @return
     *     possible object is
     *     {@link TSmestajniObjekat }
     *     
     */
    public TSmestajniObjekat getObjekat() {
        return objekat;
    }

    /**
     * Sets the value of the objekat property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSmestajniObjekat }
     *     
     */
    public void setObjekat(TSmestajniObjekat value) {
        this.objekat = value;
    }

    /**
     * Gets the value of the komentari property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the komentari property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKomentari().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TKomentar }
     * 
     * 
     */
    public List<TKomentar> getKomentari() {
        if (komentari == null) {
            komentari = new ArrayList<TKomentar>();
        }
        return this.komentari;
    }

    /**
     * Gets the value of the cenovnici property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cenovnici property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCenovnici().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TCenovnik }
     * 
     * 
     */
    public List<TCenovnik> getCenovnici() {
        if (cenovnici == null) {
            cenovnici = new ArrayList<TCenovnik>();
        }
        return this.cenovnici;
    }

    /**
     * Gets the value of the podrazumevaniCenovnik property.
     * 
     * @return
     *     possible object is
     *     {@link TCenovnik }
     *     
     */
    public TCenovnik getPodrazumevaniCenovnik() {
        return podrazumevaniCenovnik;
    }

    /**
     * Sets the value of the podrazumevaniCenovnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCenovnik }
     *     
     */
    public void setPodrazumevaniCenovnik(TCenovnik value) {
        this.podrazumevaniCenovnik = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the opis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpis() {
        return opis;
    }

    /**
     * Sets the value of the opis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpis(String value) {
        this.opis = value;
    }

    /**
     * Gets the value of the dodatneUsluge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dodatneUsluge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDodatneUsluge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TDodatnaUsluga }
     * 
     * 
     */
    public List<TDodatnaUsluga> getDodatneUsluge() {
        if (dodatneUsluge == null) {
            dodatneUsluge = new ArrayList<TDodatnaUsluga>();
        }
        return this.dodatneUsluge;
    }

    /**
     * Gets the value of the otkazivanje property.
     * 
     * @return
     *     possible object is
     *     {@link TOtkazivanje }
     *     
     */
    public TOtkazivanje getOtkazivanje() {
        return otkazivanje;
    }

    /**
     * Sets the value of the otkazivanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOtkazivanje }
     *     
     */
    public void setOtkazivanje(TOtkazivanje value) {
        this.otkazivanje = value;
    }

    /**
     * Gets the value of the povecanjeVeciBrojOsoba property.
     * 
     */
    public double getPovecanjeVeciBrojOsoba() {
        return povecanjeVeciBrojOsoba;
    }

    /**
     * Sets the value of the povecanjeVeciBrojOsoba property.
     * 
     */
    public void setPovecanjeVeciBrojOsoba(double value) {
        this.povecanjeVeciBrojOsoba = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
     *       &lt;attribute name="putanja" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Slike {

        @XmlValue
        protected byte[] value;
        @XmlAttribute(name = "putanja")
        protected String putanja;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setValue(byte[] value) {
            this.value = value;
        }

        /**
         * Gets the value of the putanja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPutanja() {
            return putanja;
        }

        /**
         * Sets the value of the putanja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPutanja(String value) {
            this.putanja = value;
        }

    }

}
