//created on: 14.04.2019.
package rules

//list any import classes here.

import java.util.Date

import com.project.megatravel.model.reservations.RezervacijaKorisnika

rule "Last-minute"
	agenda-group "popusti"
	salience 50
	lock-on-active true
    when	
        $rez : RezervacijaKorisnika( $datumRezervacije : datumRezervacije, popust == 0.0,  isToday($datumRezervacije), $id : id  )
    then
    	System.out.println("\nLast-minute\nDodeljen popust 50% za rezervaciju " + $id );
        modify ($rez) { setPopust(50); }

end

rule "Early bird"
	agenda-group "popusti"
	salience 25
	lock-on-active true
    when
        $rez : RezervacijaKorisnika( $datumRezervacije : datumRezervacije, popust == 0.0, earlyBird($datumRezervacije), $id : id  )
    then
        System.out.println("\nEarly bird\nDodeljen popust 25% za rezervaciju " + $id );
        modify ($rez) { setPopust(25); }

end

rule "Popust na neocenjene smestaje u istom mestu u kojem su klijenti boravili barem 6 puta kod barem 3 razlicita agenta"
	agenda-group "popusti"
	salience 60
	lock-on-active true
    when
        $rez : RezervacijaKorisnika( false, smestaj.getRejting().getBrojOcena() == 0, $smestaj : smestaj, popust == 0.0, $id : id  )
    then
        System.out.println("\nDodatni popust (1)\nDodeljen popust 60% za rezervaciju " + $id );
        modify ($rez) { setPopust(60); }

end

rule "Popust na neocenjene smestaje na lokaciji u kojoj klijenti nisu prethodno boravili, a koji su u prethodnoj godini posetili 6 ili vise razlicitih mesta"
	agenda-group "popusti"
	salience 80
	lock-on-active true
    when
        $rez : RezervacijaKorisnika( false, popust == 0.0, $id : id  )
    then
        System.out.println("\nDodatni popust (1)\nDodeljen popust 80% za rezervaciju " + $id );
        modify ($rez) { setPopust(80); }

end

rule "Halt popusti"
	agenda-group "popusti"
	salience -100
    when
        // Izvrsava se bezuslovno posle svih pravila koja pripadaju grupi "popusti"
    then
    	System.out.println("HALT");
        drools.halt();

end