//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.09 at 01:19:16 AM CEST 
//


package com.project.agentBackend.model.accomodation.managment;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.project.megatravel.model.accomodation.managment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.project.megatravel.model.accomodation.managment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUnitsResponse }
     * 
     */
    public GetUnitsResponse createGetUnitsResponse() {
        return new GetUnitsResponse();
    }

    /**
     * Create an instance of {@link GetUnitResponse }
     * 
     */
    public GetUnitResponse createGetUnitResponse() {
        return new GetUnitResponse();
    }

    /**
     * Create an instance of {@link AddUnitRequest }
     * 
     */
    public AddUnitRequest createAddUnitRequest() {
        return new AddUnitRequest();
    }

    /**
     * Create an instance of {@link GetObjectsResponse }
     * 
     */
    public GetObjectsResponse createGetObjectsResponse() {
        return new GetObjectsResponse();
    }

    /**
     * Create an instance of {@link GetObjectResponse }
     * 
     */
    public GetObjectResponse createGetObjectResponse() {
        return new GetObjectResponse();
    }

    /**
     * Create an instance of {@link GetObjectRequest }
     * 
     */
    public GetObjectRequest createGetObjectRequest() {
        return new GetObjectRequest();
    }

    /**
     * Create an instance of {@link GetObjectsRequest }
     * 
     */
    public GetObjectsRequest createGetObjectsRequest() {
        return new GetObjectsRequest();
    }

    /**
     * Create an instance of {@link AddObjectResponse }
     * 
     */
    public AddObjectResponse createAddObjectResponse() {
        return new AddObjectResponse();
    }

    /**
     * Create an instance of {@link AddUnitResponse }
     * 
     */
    public AddUnitResponse createAddUnitResponse() {
        return new AddUnitResponse();
    }

    /**
     * Create an instance of {@link GetUnitsRequest }
     * 
     */
    public GetUnitsRequest createGetUnitsRequest() {
        return new GetUnitsRequest();
    }

    /**
     * Create an instance of {@link GetUnitRequest }
     * 
     */
    public GetUnitRequest createGetUnitRequest() {
        return new GetUnitRequest();
    }

    /**
     * Create an instance of {@link AddObjectRequest }
     * 
     */
    public AddObjectRequest createAddObjectRequest() {
        return new AddObjectRequest();
    }

}
