//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.29 at 06:17:40 PM CEST 
//


package com.project.megatravel.model.messages.rating.managment;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.project.megatravel.model.messages.rating.managment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.project.megatravel.model.messages.rating.managment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMessageRequest }
     * 
     */
    public GetMessageRequest createGetMessageRequest() {
        return new GetMessageRequest();
    }

    /**
     * Create an instance of {@link GetRatingByUnitRequest }
     * 
     */
    public GetRatingByUnitRequest createGetRatingByUnitRequest() {
        return new GetRatingByUnitRequest();
    }

    /**
     * Create an instance of {@link AnswerMessageResponse }
     * 
     */
    public AnswerMessageResponse createAnswerMessageResponse() {
        return new AnswerMessageResponse();
    }

    /**
     * Create an instance of {@link GetCommentsByObjectRequest }
     * 
     */
    public GetCommentsByObjectRequest createGetCommentsByObjectRequest() {
        return new GetCommentsByObjectRequest();
    }

    /**
     * Create an instance of {@link GetCommentsByUnitRequest }
     * 
     */
    public GetCommentsByUnitRequest createGetCommentsByUnitRequest() {
        return new GetCommentsByUnitRequest();
    }

    /**
     * Create an instance of {@link GetMessageResponse }
     * 
     */
    public GetMessageResponse createGetMessageResponse() {
        return new GetMessageResponse();
    }

    /**
     * Create an instance of {@link AnswerMessageRequest }
     * 
     */
    public AnswerMessageRequest createAnswerMessageRequest() {
        return new AnswerMessageRequest();
    }

    /**
     * Create an instance of {@link GetRatingByObjectResponse }
     * 
     */
    public GetRatingByObjectResponse createGetRatingByObjectResponse() {
        return new GetRatingByObjectResponse();
    }

    /**
     * Create an instance of {@link GetCommentsByUnitResponse }
     * 
     */
    public GetCommentsByUnitResponse createGetCommentsByUnitResponse() {
        return new GetCommentsByUnitResponse();
    }

    /**
     * Create an instance of {@link GetMessagesRequest }
     * 
     */
    public GetMessagesRequest createGetMessagesRequest() {
        return new GetMessagesRequest();
    }

    /**
     * Create an instance of {@link GetRatingByUnitResponse }
     * 
     */
    public GetRatingByUnitResponse createGetRatingByUnitResponse() {
        return new GetRatingByUnitResponse();
    }

    /**
     * Create an instance of {@link GetRatingByObjectRequest }
     * 
     */
    public GetRatingByObjectRequest createGetRatingByObjectRequest() {
        return new GetRatingByObjectRequest();
    }

    /**
     * Create an instance of {@link GetMessagesResponse }
     * 
     */
    public GetMessagesResponse createGetMessagesResponse() {
        return new GetMessagesResponse();
    }

    /**
     * Create an instance of {@link GetCommentsByObjectResponse }
     * 
     */
    public GetCommentsByObjectResponse createGetCommentsByObjectResponse() {
        return new GetCommentsByObjectResponse();
    }

}
