//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.29 at 11:59:37 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.model.megatravel.project.com/accomodation", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.project.megatravel.model.accomodation;
