//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.14 at 10:13:26 AM CEST 
//


package com.project.megatravel.model.reservations;

import java.math.BigDecimal;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.project.megatravel.model.users.Korisnik;


/**
 * <p>Java class for TRezervacijaKorisnika complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TRezervacijaKorisnika">
 *   &lt;complexContent>
 *     &lt;extension base="{www.model.megatravel.project.com/reservations}TRezervacija">
 *       &lt;sequence>
 *         &lt;element name="cenaSmestaja">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="stanje">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Rezervisano"/>
 *               &lt;enumeration value="U toku"/>
 *               &lt;enumeration value="Otkazano"/>
 *               &lt;enumeration value="Realizovano"/>
 *               &lt;enumeration value="U obradi"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="korisnik" type="{www.model.megatravel.project.com/users}TKorisnik"/>
 *         &lt;element name="ocena" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="komentar" type="{www.model.megatravel.project.com/reservations}TKomentar"/>
 *       &lt;/sequence>
 *       &lt;attribute name="datumRezervacije">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *             &lt;minInclusive value="1900-01-01"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRezervacijaKorisnika", propOrder = {
    "cenaSmestaja",
    "stanje",
    "korisnik",
    "ocena",
    "komentar"
})
public class RezervacijaKorisnika
    extends Rezervacija
{

    @XmlElement(required = true)
    protected BigDecimal cenaSmestaja;
    @XmlElement(required = true)
    protected String stanje;
    @XmlElement(required = true)
    protected Korisnik korisnik;
    protected double ocena;
    @XmlElement(required = true)
    protected Komentar komentar;
    @XmlAttribute(name = "datumRezervacije")
    @XmlJavaTypeAdapter(Adapter3 .class)
    protected Date datumRezervacije;

    /**
     * Gets the value of the cenaSmestaja property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCenaSmestaja() {
        return cenaSmestaja;
    }

    /**
     * Sets the value of the cenaSmestaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCenaSmestaja(BigDecimal value) {
        this.cenaSmestaja = value;
    }

    /**
     * Gets the value of the stanje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStanje() {
        return stanje;
    }

    /**
     * Sets the value of the stanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStanje(String value) {
        this.stanje = value;
    }

    /**
     * Gets the value of the korisnik property.
     * 
     * @return
     *     possible object is
     *     {@link Korisnik }
     *     
     */
    public Korisnik getKorisnik() {
        return korisnik;
    }

    /**
     * Sets the value of the korisnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link Korisnik }
     *     
     */
    public void setKorisnik(Korisnik value) {
        this.korisnik = value;
    }

    /**
     * Gets the value of the ocena property.
     * 
     */
    public double getOcena() {
        return ocena;
    }

    /**
     * Sets the value of the ocena property.
     * 
     */
    public void setOcena(double value) {
        this.ocena = value;
    }

    /**
     * Gets the value of the komentar property.
     * 
     * @return
     *     possible object is
     *     {@link Komentar }
     *     
     */
    public Komentar getKomentar() {
        return komentar;
    }

    /**
     * Sets the value of the komentar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Komentar }
     *     
     */
    public void setKomentar(Komentar value) {
        this.komentar = value;
    }

    /**
     * Gets the value of the datumRezervacije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getDatumRezervacije() {
        return datumRezervacije;
    }

    /**
     * Sets the value of the datumRezervacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumRezervacije(Date value) {
        this.datumRezervacije = value;
    }

}
