//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.19 at 11:51:02 AM CEST 
//


package com.project.megatravel.model.accomodation;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.project.megatravel.model.accomodation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.project.megatravel.model.accomodation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SmestajniObjekat }
     * 
     */
    public SmestajniObjekat createSmestajniObjekat() {
        return new SmestajniObjekat();
    }

    /**
     * Create an instance of {@link Lokacija }
     * 
     */
    public Lokacija createLokacija() {
        return new Lokacija();
    }

    /**
     * Create an instance of {@link DodatnaUsluga }
     * 
     */
    public DodatnaUsluga createDodatnaUsluga() {
        return new DodatnaUsluga();
    }

    /**
     * Create an instance of {@link SmestajnaJedinica }
     * 
     */
    public SmestajnaJedinica createSmestajnaJedinica() {
        return new SmestajnaJedinica();
    }

    /**
     * Create an instance of {@link Otkazivanje }
     * 
     */
    public Otkazivanje createOtkazivanje() {
        return new Otkazivanje();
    }

    /**
     * Create an instance of {@link SmestajniObjekat.Slike }
     * 
     */
    public SmestajniObjekat.Slike createSmestajniObjekatSlike() {
        return new SmestajniObjekat.Slike();
    }

    /**
     * Create an instance of {@link TipSmestaja }
     * 
     */
    public TipSmestaja createTipSmestaja() {
        return new TipSmestaja();
    }

    /**
     * Create an instance of {@link KategorijaSm }
     * 
     */
    public KategorijaSm createKategorijaSm() {
        return new KategorijaSm();
    }

    /**
     * Create an instance of {@link Cenovnik }
     * 
     */
    public Cenovnik createCenovnik() {
        return new Cenovnik();
    }

    /**
     * Create an instance of {@link Rejting }
     * 
     */
    public Rejting createRejting() {
        return new Rejting();
    }

    /**
     * Create an instance of {@link TPolozaj }
     * 
     */
    public TPolozaj createTPolozaj() {
        return new TPolozaj();
    }

}
