//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.12 at 12:11:32 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.megatravel.com/tim41/pretraga", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.project.megaTravel.model.tim41.pretraga;
