//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.12 at 12:11:32 AM CEST 
//


package com.project.megaTravel.model.tim41.pretraga;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.project.megaTravel.model.tim41.TDodatnaUsluga;
import com.project.megaTravel.model.tim41.TLokacija;


/**
 * <p>Java class for TPretraga complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPretraga">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Lokacija" type="{www.megatravel.com/tim41}TLokacija"/>
 *         &lt;element name="Dolazak" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Odlazak" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="BrojOsoba">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TipSmestaja" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Hotel"/>
 *               &lt;enumeration value="Apartman"/>
 *               &lt;enumeration value="Bed&amp;Breakfast"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="KategorijaSmestaja" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="NA"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Udaljenost" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BesplatnoOtkazivanje" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="OtkazivanjePre" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DodatneUsluge" type="{www.megatravel.com/tim41}TDodatnaUsluga" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPretraga", propOrder = {
    "lokacija",
    "dolazak",
    "odlazak",
    "brojOsoba",
    "tipSmestaja",
    "kategorijaSmestaja",
    "udaljenost",
    "besplatnoOtkazivanje",
    "otkazivanjePre",
    "dodatneUsluge"
})
public class TPretraga {

    @XmlElement(name = "Lokacija", required = true)
    protected TLokacija lokacija;
    @XmlElement(name = "Dolazak", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dolazak;
    @XmlElement(name = "Odlazak", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar odlazak;
    @XmlElement(name = "BrojOsoba", required = true)
    protected BigInteger brojOsoba;
    @XmlElement(name = "TipSmestaja")
    protected String tipSmestaja;
    @XmlElement(name = "KategorijaSmestaja")
    protected String kategorijaSmestaja;
    @XmlElement(name = "Udaljenost")
    protected Double udaljenost;
    @XmlElement(name = "BesplatnoOtkazivanje", defaultValue = "false")
    protected Boolean besplatnoOtkazivanje;
    @XmlElement(name = "OtkazivanjePre")
    protected BigInteger otkazivanjePre;
    @XmlElement(name = "DodatneUsluge")
    protected List<TDodatnaUsluga> dodatneUsluge;

    /**
     * Gets the value of the lokacija property.
     * 
     * @return
     *     possible object is
     *     {@link TLokacija }
     *     
     */
    public TLokacija getLokacija() {
        return lokacija;
    }

    /**
     * Sets the value of the lokacija property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLokacija }
     *     
     */
    public void setLokacija(TLokacija value) {
        this.lokacija = value;
    }

    /**
     * Gets the value of the dolazak property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDolazak() {
        return dolazak;
    }

    /**
     * Sets the value of the dolazak property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDolazak(XMLGregorianCalendar value) {
        this.dolazak = value;
    }

    /**
     * Gets the value of the odlazak property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOdlazak() {
        return odlazak;
    }

    /**
     * Sets the value of the odlazak property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOdlazak(XMLGregorianCalendar value) {
        this.odlazak = value;
    }

    /**
     * Gets the value of the brojOsoba property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojOsoba() {
        return brojOsoba;
    }

    /**
     * Sets the value of the brojOsoba property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojOsoba(BigInteger value) {
        this.brojOsoba = value;
    }

    /**
     * Gets the value of the tipSmestaja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipSmestaja() {
        return tipSmestaja;
    }

    /**
     * Sets the value of the tipSmestaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipSmestaja(String value) {
        this.tipSmestaja = value;
    }

    /**
     * Gets the value of the kategorijaSmestaja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKategorijaSmestaja() {
        return kategorijaSmestaja;
    }

    /**
     * Sets the value of the kategorijaSmestaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKategorijaSmestaja(String value) {
        this.kategorijaSmestaja = value;
    }

    /**
     * Gets the value of the udaljenost property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getUdaljenost() {
        return udaljenost;
    }

    /**
     * Sets the value of the udaljenost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setUdaljenost(Double value) {
        this.udaljenost = value;
    }

    /**
     * Gets the value of the besplatnoOtkazivanje property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBesplatnoOtkazivanje() {
        return besplatnoOtkazivanje;
    }

    /**
     * Sets the value of the besplatnoOtkazivanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBesplatnoOtkazivanje(Boolean value) {
        this.besplatnoOtkazivanje = value;
    }

    /**
     * Gets the value of the otkazivanjePre property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOtkazivanjePre() {
        return otkazivanjePre;
    }

    /**
     * Sets the value of the otkazivanjePre property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOtkazivanjePre(BigInteger value) {
        this.otkazivanjePre = value;
    }

    /**
     * Gets the value of the dodatneUsluge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dodatneUsluge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDodatneUsluge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TDodatnaUsluga }
     * 
     * 
     */
    public List<TDodatnaUsluga> getDodatneUsluge() {
        if (dodatneUsluge == null) {
            dodatneUsluge = new ArrayList<TDodatnaUsluga>();
        }
        return this.dodatneUsluge;
    }

}
