
package com.project.megatravel.model.proxyservices.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientService", targetNamespace = "http://model.megatravel.project.com/proxyServices/client")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientService {


    /**
     * 
     * @param testClient
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "testClientResponse", targetNamespace = "http://model.megatravel.project.com/proxyServices/client", partName = "testClientResponse")
    @Action(input = "http://model.megatravel.project.com/proxyServices/client/ClientService/testClientRequest", output = "http://model.megatravel.project.com/proxyServices/client/ClientService/testClientResponse")
    public String testClient(
        @WebParam(name = "testClient", targetNamespace = "http://model.megatravel.project.com/proxyServices/client", partName = "testClient")
        String testClient);

}
