//created on: 02.06.2019.
package rules

//list any import classes here.

import org.apache.commons.lang.time.DateUtils

import com.project.megatravel.model.reservations.RezervacijaKorisnika
import com.project.megatravel.model.accomodation.SmestajniObjekat
import com.project.megatravel.model.accomodation.SmestajnaJedinica

//declare any global variables here

//global Set lojalni;

global Double predlog;
// Lista za preporuke za popust
global List lista;
// Lista za preporuke za upozorenja
global List lista2;

rule "Nema rezervacija u poslednjih 15 dana i cena veca od prosecne"
	agenda-group "agent"
	lock-on-active
	salience 10
    when
        // rezervacije od poslednjih 15 dana
        $rez15: List() from collect ( RezervacijaKorisnika( 
    	$dt: DateUtils.truncate(DateUtils.addDays(datumRezervacije, 15), Calendar.DAY_OF_MONTH),
		eval($dt.after(new Date()))))
		// Objekti sa rezervacijama
    	$smestaji : Set() from accumulate (
			RezervacijaKorisnika (
				$id : smestaj.getSObjekat().getId()
			) from $rez15,
			collectSet($id)
		)
		// Objekti koji nemaju rezervacije u prethodnih 15 dana
		$so : SmestajniObjekat( id not memberOf $smestaji, $lok: lokacija )
		$mojeJedinice: List() from collect ( SmestajnaJedinica( sObjekat==$so ) )
		$jediniceUMestu: List() from collect ( SmestajnaJedinica( 
		sObjekat!=$so, sObjekat.getLokacija()==$lok ) )
		
		Number ($avg: doubleValue) from accumulate (
    		SmestajnaJedinica(
    			$price: podrazumevaniCenovnik.getCena().getIznos()
    		) from $jediniceUMestu,
    		average($price)
    	)
    	
    	Number ($avgMoje: doubleValue) from accumulate (
    		SmestajnaJedinica(
    			$price2: podrazumevaniCenovnik.getCena().getIznos()
    		) from $mojeJedinice,
    		average($price2)
    	)
    	
    	eval($avgMoje > $avg)
		
    then
    	lista2.add($so.getAgent());
    	drools.getKnowledgeRuntime().setGlobal("lista", lista2); 
        System.out.println("Nema rezervacije " + $so.getId());
        System.out.println("Upozoriti agenta");

end

rule "Preporuka za snizenje"
    agenda-group "agent"
    lock-on-active
    salience 10
    when
        $sj: SmestajnaJedinica(  )
    	$rezj: List() from collect ( RezervacijaKorisnika( smestaj==$sj ) )
    	eval ( imaRezervacija($sj, $rezj)==false )
    	Number ($avg: doubleValue) from accumulate (
    		SmestajnaJedinica(
    			this != $sj,
    			$price: podrazumevaniCenovnik.getCena().getIznos(),
    			// Uzmi u obzir samo one iste kategorije
    			sObjekat.getKategorija()==$sj.getSObjekat().getKategorija(),
    			// Uzmi u obzir samo one sa slicnim ocenama
    			Math.abs(
    			(double)$sj.getRejting().getSumaOcena()/$sj.getRejting().getBrojOcena()-
    			(double)rejting.getSumaOcena()/rejting.getBrojOcena() )
    			<=0.5
    		),
    		average($price)
    	)
    	// Provera da li je cena vec dovoljno atraktivna
    	eval ( $sj.getPodrazumevaniCenovnik().getCena().getIznos()/$avg - 1 > 0)
    then
    	lista.add($sj);
    	drools.getKnowledgeRuntime().setGlobal("lista", lista);
    
    	System.out.println("--------");
    	System.out.println($sj.getPodrazumevaniCenovnik().getCena().getIznos());
    	System.out.println($avg);
    	double pr = $sj.getPodrazumevaniCenovnik().getCena().getIznos()/$avg - 1;
    	
        System.out.println("Nema rezervacije u buducnosti - " + $sj.getId());
        //if (pr > 0) {
	    System.out.println("Predloziti popust " + pr * 100 + "%");
    	//} else {
    	//	System.out.println("Cena je vec dovoljno atraktivna");
    	//}
end

// Proba za template
/*rule "Lojalnost"
no-loop true
agenda-group "lojalnost"
salience 10
when
    $rez: RezervacijaKorisnika( $k: korisnik, (lojalni.contains($k)==false), popust==0.0, $agent: smestaj.getSObjekat().getAgent() )
    Number(intValue >= 3) from accumulate (
    	$rez2: RezervacijaKorisnika(
    		korisnik == $k,
    		smestaj.getSObjekat().getAgent() == $agent
    	), count(1)
    )
then
	System.out.println("Granica prevazidjena ");
	System.out.println("Dodeli popust " + lojalni.contains($k));
	lojalni.add($k);
	kcontext.getKieRuntime().setGlobal( "lojalni", lojalni );
    $rez.setPopust(10);   
end*/

// Halt
rule "Halt agent"
	agenda-group "agent"
	salience -100
    when
        // Izvrsava se bezuslovno posle svih pravila koja pripadaju grupi "agent"
    then
    	System.out.println("HALT");
        drools.halt();

end
