//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.14 at 10:13:26 AM CEST 
//


package com.project.megatravel.model.users;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.project.megatravel.model.accomodation.SmestajniObjekat;
import com.project.megatravel.model.reservations.Rezervacija;


/**
 * <p>Java class for TAgent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAgent">
 *   &lt;complexContent>
 *     &lt;extension base="{www.model.megatravel.project.com/users}TKorisnik">
 *       &lt;sequence>
 *         &lt;element name="poslovniMaticniBroj">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="smestajniObjekti" type="{www.model.megatravel.project.com/accomodation}TSmestajniObjekat" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="rezervacije" type="{www.model.megatravel.project.com/reservations}TRezervacija" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="filteriPoruka" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAgent", propOrder = {
    "poslovniMaticniBroj",
    "smestajniObjekti",
    "rezervacije",
    "filteriPoruka"
})
public class Agent
    extends Korisnik
{

    @XmlElement(required = true)
    protected BigInteger poslovniMaticniBroj;
    protected List<SmestajniObjekat> smestajniObjekti;
    protected List<Rezervacija> rezervacije;
    protected List<String> filteriPoruka;

    /**
     * Gets the value of the poslovniMaticniBroj property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPoslovniMaticniBroj() {
        return poslovniMaticniBroj;
    }

    /**
     * Sets the value of the poslovniMaticniBroj property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPoslovniMaticniBroj(BigInteger value) {
        this.poslovniMaticniBroj = value;
    }

    /**
     * Gets the value of the smestajniObjekti property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the smestajniObjekti property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSmestajniObjekti().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmestajniObjekat }
     * 
     * 
     */
    public List<SmestajniObjekat> getSmestajniObjekti() {
        if (smestajniObjekti == null) {
            smestajniObjekti = new ArrayList<SmestajniObjekat>();
        }
        return this.smestajniObjekti;
    }

    /**
     * Gets the value of the rezervacije property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rezervacije property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRezervacije().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rezervacija }
     * 
     * 
     */
    public List<Rezervacija> getRezervacije() {
        if (rezervacije == null) {
            rezervacije = new ArrayList<Rezervacija>();
        }
        return this.rezervacije;
    }

    /**
     * Gets the value of the filteriPoruka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filteriPoruka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilteriPoruka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFilteriPoruka() {
        if (filteriPoruka == null) {
            filteriPoruka = new ArrayList<String>();
        }
        return this.filteriPoruka;
    }

}
