//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.12 at 12:59:01 AM CEST 
//


package com.project.megaTravel.model.tim41.reservations;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.project.megaTravel.model.tim41.users.TKorisnik;


/**
 * <p>Java class for TRezervacijaKorisnika complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TRezervacijaKorisnika">
 *   &lt;complexContent>
 *     &lt;extension base="{www.megatravel.com/tim41/reservations}TRezervacija">
 *       &lt;sequence>
 *         &lt;element name="CenaSmestaja">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="StanjeRezervacije">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Rezervisano"/>
 *               &lt;enumeration value="U toku"/>
 *               &lt;enumeration value="Otkazano"/>
 *               &lt;enumeration value="Realizovano"/>
 *               &lt;enumeration value="U obradi"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Korisnik" type="{www.megatravel.com/tim41/users}TKorisnik"/>
 *         &lt;element name="Ocena" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Komentar" type="{www.megatravel.com/tim41/reservations}TKomentar"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DatumRezervacije" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRezervacijaKorisnika", propOrder = {
    "cenaSmestaja",
    "stanjeRezervacije",
    "korisnik",
    "ocena",
    "komentar"
})
public class TRezervacijaKorisnika
    extends TRezervacija
{

    @XmlElement(name = "CenaSmestaja", required = true)
    protected BigDecimal cenaSmestaja;
    @XmlElement(name = "StanjeRezervacije", required = true)
    protected String stanjeRezervacije;
    @XmlElement(name = "Korisnik", required = true)
    protected TKorisnik korisnik;
    @XmlElement(name = "Ocena")
    protected double ocena;
    @XmlElement(name = "Komentar", required = true)
    protected TKomentar komentar;
    @XmlAttribute(name = "DatumRezervacije")
    @XmlSchemaType(name = "anySimpleType")
    protected String datumRezervacije;

    /**
     * Gets the value of the cenaSmestaja property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCenaSmestaja() {
        return cenaSmestaja;
    }

    /**
     * Sets the value of the cenaSmestaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCenaSmestaja(BigDecimal value) {
        this.cenaSmestaja = value;
    }

    /**
     * Gets the value of the stanjeRezervacije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStanjeRezervacije() {
        return stanjeRezervacije;
    }

    /**
     * Sets the value of the stanjeRezervacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStanjeRezervacije(String value) {
        this.stanjeRezervacije = value;
    }

    /**
     * Gets the value of the korisnik property.
     * 
     * @return
     *     possible object is
     *     {@link TKorisnik }
     *     
     */
    public TKorisnik getKorisnik() {
        return korisnik;
    }

    /**
     * Sets the value of the korisnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKorisnik }
     *     
     */
    public void setKorisnik(TKorisnik value) {
        this.korisnik = value;
    }

    /**
     * Gets the value of the ocena property.
     * 
     */
    public double getOcena() {
        return ocena;
    }

    /**
     * Sets the value of the ocena property.
     * 
     */
    public void setOcena(double value) {
        this.ocena = value;
    }

    /**
     * Gets the value of the komentar property.
     * 
     * @return
     *     possible object is
     *     {@link TKomentar }
     *     
     */
    public TKomentar getKomentar() {
        return komentar;
    }

    /**
     * Sets the value of the komentar property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKomentar }
     *     
     */
    public void setKomentar(TKomentar value) {
        this.komentar = value;
    }

    /**
     * Gets the value of the datumRezervacije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatumRezervacije() {
        return datumRezervacije;
    }

    /**
     * Sets the value of the datumRezervacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumRezervacije(String value) {
        this.datumRezervacije = value;
    }

}
